name: Deploy Fly High
on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Setup Node 21
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Run Linting Locally
        run: npm run eslint

      - name: Run Tests Locally
        run: npm run test

      - name: Run Build Locally
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: test
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: |
          npm install --global vercel@latest
          vercel --prod --token=$VERCEL_TOKEN --confirm